name: Build Indico plugins

env:
  TZ: Europe/Zurich

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.12'
        description: The Python version to use during the build
      node-version:
        type: string
        default: '22.x'
        description: The node version to use during the build
      scripts-repo:
        type: string
        default: indico/indico-gh-actions
        description: The GitHub repo containing this action and its related scripts
      extra-plugins-repo:
        type: string
        default: ''
        description: A GitHub repo with additional plugins that might be required as dependencies
      extra-plugins-dir:
        type: string
        default: extra
        description: The name of the additional set of plugins (used as a directory name)
      add-version-suffix:
        type: boolean
        default: true
        description: Whether to append a version suffix containing commit hash and build date to the package version
      artifact-retention-days:
        type: number
        default: 1
        description: Number of days to keep the individual plugin wheel artifacts
      directory:
        type: string
        required: true
        description: The name of the plugin / set of plugins (used as a directory name)
      plugin:
        type: string
        description: The plugin to build when building a specific one (via workflow_dispatch)

permissions:
  contents: read

jobs:
  plugin-matrix:
    name: Generate matrix
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'build-wheel')
    outputs:
      matrix: ${{ steps.plugin-matrix.outputs.matrix }}
      source-date-epoch: ${{ steps.time.outputs.time }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          path: plugins
          persist-credentials: false
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          path: .workflow
          repository: ${{ inputs.scripts-repo }}
          persist-credentials: false
      - name: Set up Python 🐍
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ inputs.python-version }}
      - name: Generate matrix
        id: plugin-matrix
        working-directory: plugins
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event_name == 'pull_request' && github.event.pull_request.number }}
          PLUGIN_NAME: ${{ github.event_name == 'workflow_dispatch' && inputs.plugin }}
        run: python $GITHUB_WORKSPACE/.workflow/scripts/generate_matrix.py
      - name: Get current time
        id: time
        run: echo "time=$(date +%s)" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.plugin }} 🛠
    runs-on: ubuntu-22.04
    needs: plugin-matrix
    if: needs.plugin-matrix.outputs.matrix != ''
    strategy:
      matrix: ${{ fromJson(needs.plugin-matrix.outputs.matrix) }}
    env:
      SOURCE_DATE_EPOCH: ${{ needs.plugin-matrix.outputs.source-date-epoch }}
    steps:
      - name: Checkout plugins
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          path: plugins/${{ inputs.directory }}
          # prefer head commit over merge commit in case of PRs
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
          persist-credentials: false

      - name: Checkout workflow
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          path: .workflow
          repository: ${{ inputs.scripts-repo }}
          persist-credentials: false

      - name: Pick Indico core repo
        id: core-repo
        env:
          GH_TOKEN: ${{ github.token }}
          PR_BODY: ${{ github.event_name == 'pull_request' && github.event.pull_request.body }}
          PR_BASE_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref }}
        run: python $GITHUB_WORKSPACE/.workflow/scripts/get_core_repo.py indico/indico INDICO

      - name: Pick extra plugins repo
        id: extra-plugins-repo
        if: inputs.extra-plugins-repo
        env:
          GH_TOKEN: ${{ github.token }}
          PR_BODY: ${{ github.event_name == 'pull_request' && github.event.pull_request.body }}
          PR_BASE_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref }}
          INPUTS_EXTRA_PLUGINS_REPO: ${{ inputs.extra-plugins-repo }}
        run: python $GITHUB_WORKSPACE/.workflow/scripts/get_core_repo.py ${INPUTS_EXTRA_PLUGINS_REPO} PLUGINS

      - name: Checkout core
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          path: indico
          repository: ${{ steps.core-repo.outputs.INDICO_REPO }}
          ref: ${{ steps.core-repo.outputs.INDICO_BRANCH }}
          persist-credentials: false

      - name: Checkout extra plugins
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        if: inputs.extra-plugins-repo
        with:
          path: plugins/${{ inputs.extra-plugins-dir }}
          repository: ${{ steps.extra-plugins-repo.outputs.PLUGINS_REPO }}
          ref: ${{ steps.extra-plugins-repo.outputs.PLUGINS_BRANCH }}
          persist-credentials: false

      - name: Set up Python 🐍
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          cache-dependency-glob: |
            indico/requirements*.txt
            plugins/**/pyproject.toml

      - name: Setup Node
        if: matrix.assets
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: indico/package-lock.json

      - name: Install build deps 🔧
        working-directory: indico
        run: |
          sudo apt-get install libpq-dev
          uv pip install --system -e '.[dev]'

      - name: Install npm deps ☕
        if: matrix.assets
        working-directory: indico
        run: npm ci

      - name: Install plugin deps 🔧
        if: matrix.install && toJson(matrix.deps) != '[]'
        run: |
          for dep in ${{ join(matrix.deps, ' ') }}; do
            if [[ -e plugins/${INPUTS_DIRECTORY}/$dep ]]; then
              uv pip install --system -e plugins/${INPUTS_DIRECTORY}/$dep/
            else
              uv pip install --system -e plugins/${INPUTS_EXTRA_PLUGINS_DIR}/$dep/
            fi
          done
        env:
          INPUTS_DIRECTORY: ${{ inputs.directory }}
          INPUTS_EXTRA_PLUGINS_DIR: ${{ inputs.extra-plugins-dir }}

      - name: Install plugin 🔧
        if: matrix.install
        working-directory: plugins/${{ inputs.directory }}
        run: uv pip install --system -e ${{ matrix.path || '.' }}/

      # XXX this is already done by build-wheel.py (but w/o react i18n which we don't use in plugins yet)
      # - name: Compile translations 🏴‍☠️
      #   if: matrix.i18n
      #   working-directory: indico
      #   run: indico i18n compile plugin ../plugins/${{ inputs.directory }}/${{ matrix.path }}

      - name: Build wheel 🏗
        working-directory: indico
        run: >-
          ./bin/maintenance/build-wheel.py
          plugin
          ../plugins/${INPUTS_DIRECTORY}/${MATRIX_PATH}
          ${{ inputs.add-version-suffix && '--add-version-suffix' || '' }}
        env:
          INPUTS_DIRECTORY: ${{ inputs.directory }}
          MATRIX_PATH: ${{ matrix.path }}

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        name: Upload build artifacts 📦
        with:
          name: ${{ matrix.single && 'plugin-wheel' || format('plugin-wheel-{0}', matrix.plugin) }}
          retention-days: ${{ inputs.artifact-retention-days }}
          path: ./indico/dist
